spring.application.name=ascenderp
spring.datasource.url=jdbc:mysql://localhost:3306/ascenderp
spring.datasource.username=root
spring.datasource.password=Aniruddha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080